name: AzureCard-DeployRelease
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 12
    steps:
      - name: Create Tag
        uses: phish108/autotag-action@1.1.47
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: true
          release-branch: main
          bump: minor
      - name: Create Release
        uses: actions/checkout@v3
      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" -x ".github/*"
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.tagger.outputs.new-tag }}"
          prerelease: false
          title: "v${{ steps.tagger.outputs.new-tag }}-${{ github.event.repository.name }}.zip"
          files: |
            ${{ github.event.repository.name }}.zip